name: Deploy to Vercel

on:
  workflow_run:
    workflows: ['DB Sync']
    types:
      - completed

jobs:
  vercel-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Clean Install
        run: npm ci

      - name: Check Next.js Configuration
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Checking Next.js config:"
          npx next telemetry status

      - name: Build Project
        env:
          DATABASE_URL: ${{ secrets.NEON_DATABASE_URL }}
        run: npm run build

      - name: Deploy to Vercel
        run: npx vercel@25.1.0 --prod
        env:
          VERCEL_TOKEN: ${{ secrets.GH_DEPLOYMENT_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID}}
